### ISSUE TITLE
Not startup unicorn after reboot

### ISSUE THREAD

**Issue by khmelevskii** [caleb/freebsd-unicorn#3]
Script working good, but after reboot unicorn not starup.

**Comment by caleb** [comment]
Hmm, I can check that out.

Did you put the appropriate “REQUIRE:” line at the top to make sure your database is started before unicorn? This will cause problems on startup.

Something like:

# REQUIRE: LOGIN postgresql

or

# REQUIRE: LOGIN mysql-server

If you have that, I can look at the script to diagnose the problem.

**Comment by caleb** [comment]
I'm going to close this issue since it's been open for so long.
